baseurl = "/"
languageCode = "en-us"
title = "Classic"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
disableKinds = ["taxonomy", "term", "RSS"]

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Built with [Hugo](https://gohugo.io/) | Deployed with [Netlify](https://www.netlify.com/) | Theme by [Goodroot](https://keybase.io/goodroot)"
    custom_css = ["css/theme-override.css"]
